### ISSUE TITLE
Missing Entities

### ISSUE THREAD

**Issue by dhoffmann1979** [nigl/homeassistant_eta_integration#1]
I installed the Integration and everything works fine, but some of the values from ETA API are missing, f.e. <object uri="/120/10601/0/0/12197" name="Außentemperatur"/></object>

How can i fix this ?

**Comment by nigl** [comment]
@dhoffmann1979 
Which values are missing?

**Comment by nigl** [comment]
@dhoffmann1979  I released a new version (0.0.2) it should work now.
If not please reopen the issue
