### ISSUE TITLE
outside temperature

### ISSUE THREAD

**Issue by joeto60** [nigl/homeassistant_eta_integration#2]
Good morning, nig!
Thanks to your project I was able to connect my boiler ETA.
I only have one problem I don't see the outside temperature.
The menu of my boiler is this (in Italian)
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<eta xmlns="http://www.eta.co.at/rest/v1" version="1.0">
<menu>
<fub uri="/120/10251" name="Puffer">
<object uri="/120/10251/0/0/12207" name="Puffer">
<object uri="/120/10251/0/0/12242" name="Puffer superiore">
<object uri="/120/10251/12130/0/0" name="Tempi di carico">
<object uri="/120/10251/12130/0/1109" name="Stato attuale"/>
<object uri="/120/10251/12130/0/1110" name="Temperatura"/>
<object uri="/120/10251/12130/0/1081" name="Lunedì">
<object uri="/120/10251/12130/0/1111" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12130/0/1082" name="Fascia oraria 1"/>
<object uri="/120/10251/12130/0/1083" name="Fascia oraria 2"/>
<object uri="/120/10251/12130/0/1084" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12130/0/1085" name="Martedì">
<object uri="/120/10251/12130/0/1112" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12130/0/1086" name="Fascia oraria 1"/>
<object uri="/120/10251/12130/0/1087" name="Fascia oraria 2"/>
<object uri="/120/10251/12130/0/1088" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12130/0/1089" name="Mercoledì">
<object uri="/120/10251/12130/0/1113" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12130/0/1090" name="Fascia oraria 1"/>
<object uri="/120/10251/12130/0/1091" name="Fascia oraria 2"/>
<object uri="/120/10251/12130/0/1092" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12130/0/1093" name="Giovedì">
<object uri="/120/10251/12130/0/1114" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12130/0/1094" name="Fascia oraria 1"/>
<object uri="/120/10251/12130/0/1095" name="Fascia oraria 2"/>
<object uri="/120/10251/12130/0/1096" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12130/0/1097" name="Venerdì">
<object uri="/120/10251/12130/0/1115" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12130/0/1098" name="Fascia oraria 1"/>
<object uri="/120/10251/12130/0/1099" name="Fascia oraria 2"/>
<object uri="/120/10251/12130/0/1100" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12130/0/1101" name="Sabato">
<object uri="/120/10251/12130/0/1116" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12130/0/1102" name="Fascia oraria 1"/>
<object uri="/120/10251/12130/0/1103" name="Fascia oraria 2"/>
<object uri="/120/10251/12130/0/1104" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12130/0/1105" name="Domenica">
<object uri="/120/10251/12130/0/1117" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12130/0/1106" name="Fascia oraria 1"/>
<object uri="/120/10251/12130/0/1107" name="Fascia oraria 2"/>
<object uri="/120/10251/12130/0/1108" name="Fascia oraria 3"/>
</object>
</object>
<object uri="/120/10251/0/0/12211" name="Puffer superiore min"/>
<object uri="/120/10251/0/0/12209" name="Valore nominale puffer"/>
<object uri="/120/10251/0/0/12667" name="Caricare con altre utenze">
<object uri="/120/10251/0/0/13535" name="Differenza di ins."/>
</object>
<object uri="/120/10251/0/0/12932" name="Caricamento con generatore">
<object uri="/120/10251/0/0/13535" name="Differenza di ins."/>
</object>
</object>
<object uri="/120/10251/0/0/12244" name="Puffer inferiore">
<object uri="/120/10251/0/0/12212" name="Puffer inferiore OFF"/>
</object>
<object uri="/120/10251/0/0/12533" name="Potenza richiesta"/>
<object uri="/120/10251/0/0/12317" name="Cascata"/>
<object uri="/120/10251/0/0/12270" name="Abilitazione bruciatore">
<object uri="/120/10251/0/0/12524" name="Avvia bruciatore al di sotto"/>
</object>
<object uri="/120/10251/0/0/12652" name="Smaltimento solare">
<object uri="/120/10251/0/0/12683" name="Attivare?"/>
<object uri="/120/10251/0/0/12645" name="... fino puffer max"/>
</object>
<object uri="/120/10251/0/0/13026" name="Carica extra">
<object uri="/120/10251/0/0/13010" name="Attivare carica extra?"/>
<object uri="/120/10251/0/0/13028" name="Puffer superiore min"/>
<object uri="/120/10251/0/0/13027" name="Puffer inferiore OFF"/>
<object uri="/120/10251/0/0/13029" name="Carico Extra a partire da"/>
<object uri="/120/10251/0/0/13025" name="Tasto Carico"/>
</object>
</object>
<object uri="/120/10251/0/0/12129" name="Boiler ACS">
<object uri="/120/10251/12235/0/0" name="Tempi di carico">
<object uri="/120/10251/12235/0/1109" name="Stato attuale"/>
<object uri="/120/10251/12235/0/1110" name="Temperatura"/>
<object uri="/120/10251/12235/0/1081" name="Lunedì">
<object uri="/120/10251/12235/0/1111" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12235/0/1082" name="Fascia oraria 1"/>
<object uri="/120/10251/12235/0/1083" name="Fascia oraria 2"/>
<object uri="/120/10251/12235/0/1084" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12235/0/1085" name="Martedì">
<object uri="/120/10251/12235/0/1112" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12235/0/1086" name="Fascia oraria 1"/>
<object uri="/120/10251/12235/0/1087" name="Fascia oraria 2"/>
<object uri="/120/10251/12235/0/1088" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12235/0/1089" name="Mercoledì">
<object uri="/120/10251/12235/0/1113" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12235/0/1090" name="Fascia oraria 1"/>
<object uri="/120/10251/12235/0/1091" name="Fascia oraria 2"/>
<object uri="/120/10251/12235/0/1092" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12235/0/1093" name="Giovedì">
<object uri="/120/10251/12235/0/1114" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12235/0/1094" name="Fascia oraria 1"/>
<object uri="/120/10251/12235/0/1095" name="Fascia oraria 2"/>
<object uri="/120/10251/12235/0/1096" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12235/0/1097" name="Venerdì">
<object uri="/120/10251/12235/0/1115" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12235/0/1098" name="Fascia oraria 1"/>
<object uri="/120/10251/12235/0/1099" name="Fascia oraria 2"/>
<object uri="/120/10251/12235/0/1100" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12235/0/1101" name="Sabato">
<object uri="/120/10251/12235/0/1116" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12235/0/1102" name="Fascia oraria 1"/>
<object uri="/120/10251/12235/0/1103" name="Fascia oraria 2"/>
<object uri="/120/10251/12235/0/1104" name="Fascia oraria 3"/>
</object>
<object uri="/120/10251/12235/0/1105" name="Domenica">
<object uri="/120/10251/12235/0/1117" name="Temperatura d'attenuazione"/>
<object uri="/120/10251/12235/0/1106" name="Fascia oraria 1"/>
<object uri="/120/10251/12235/0/1107" name="Fascia oraria 2"/>
<object uri="/120/10251/12235/0/1108" name="Fascia oraria 3"/>
</object>
</object>
<object uri="/120/10251/0/0/12133" name="Differenza di ins."/>
<object uri="/120/10251/0/0/12132" name="Valore nominale boiler ACS"/>
<object uri="/120/10251/0/0/12271" name="Boiler ACS"/>
</object>
<object uri="/120/10251/0/0/12182" name="Altro">
<object uri="/120/10251/0/0/12134" name="Tasto Carico"/>
</object>
</fub>
<fub uri="/120/10101" name="Riscal.">
<object uri="/120/10101/0/0/12090" name="Circuito di riscaldamento">
<object uri="/120/10101/0/0/12092" name="Funzionamento"/>
<object uri="/120/10101/12113/0/0" name="Tempi di riscaldamento">
<object uri="/120/10101/12113/0/1109" name="Stato attuale"/>
<object uri="/120/10101/12113/0/1110" name="Temperatura"/>
<object uri="/120/10101/12113/0/1081" name="Lunedì">
<object uri="/120/10101/12113/0/1111" name="Temperatura d'attenuazione"/>
<object uri="/120/10101/12113/0/1082" name="Fascia oraria 1"/>
<object uri="/120/10101/12113/0/1083" name="Fascia oraria 2"/>
<object uri="/120/10101/12113/0/1084" name="Fascia oraria 3"/>
</object>
<object uri="/120/10101/12113/0/1085" name="Martedì">
<object uri="/120/10101/12113/0/1112" name="Temperatura d'attenuazione"/>
<object uri="/120/10101/12113/0/1086" name="Fascia oraria 1"/>
<object uri="/120/10101/12113/0/1087" name="Fascia oraria 2"/>
<object uri="/120/10101/12113/0/1088" name="Fascia oraria 3"/>
</object>
<object uri="/120/10101/12113/0/1089" name="Mercoledì">
<object uri="/120/10101/12113/0/1113" name="Temperatura d'attenuazione"/>
<object uri="/120/10101/12113/0/1090" name="Fascia oraria 1"/>
<object uri="/120/10101/12113/0/1091" name="Fascia oraria 2"/>
<object uri="/120/10101/12113/0/1092" name="Fascia oraria 3"/>
</object>
<object uri="/120/10101/12113/0/1093" name="Giovedì">
<object uri="/120/10101/12113/0/1114" name="Temperatura d'attenuazione"/>
<object uri="/120/10101/12113/0/1094" name="Fascia oraria 1"/>
<object uri="/120/10101/12113/0/1095" name="Fascia oraria 2"/>
<object uri="/120/10101/12113/0/1096" name="Fascia oraria 3"/>
</object>
<object uri="/120/10101/12113/0/1097" name="Venerdì">
<object uri="/120/10101/12113/0/1115" name="Temperatura d'attenuazione"/>
<object uri="/120/10101/12113/0/1098" name="Fascia oraria 1"/>
<object uri="/120/10101/12113/0/1099" name="Fascia oraria 2"/>
<object uri="/120/10101/12113/0/1100" name="Fascia oraria 3"/>
</object>
<object uri="/120/10101/12113/0/1101" name="Sabato">
<object uri="/120/10101/12113/0/1116" name="Temperatura d'attenuazione"/>
<object uri="/120/10101/12113/0/1102" name="Fascia oraria 1"/>
<object uri="/120/10101/12113/0/1103" name="Fascia oraria 2"/>
<object uri="/120/10101/12113/0/1104" name="Fascia oraria 3"/>
</object>
<object uri="/120/10101/12113/0/1105" name="Domenica">
<object uri="/120/10101/12113/0/1117" name="Temperatura d'attenuazione"/>
<object uri="/120/10101/12113/0/1106" name="Fascia oraria 1"/>
<object uri="/120/10101/12113/0/1107" name="Fascia oraria 2"/>
<object uri="/120/10101/12113/0/1108" name="Fascia oraria 3"/>
</object>
</object>
<object uri="/120/10101/0/0/12634" name="Ambiente">
<object uri="/120/10101/0/0/12127" name="Valore nominale ambiente"/>
</object>
<object uri="/120/10101/0/0/12241" name="Mandata"/>
<object uri="/120/10101/0/0/12111" name="Curva termica">
<object uri="/120/10101/0/0/12240" name="Posizione cursore"/>
<object uri="/120/10101/0/0/12104" name="Mandata a -10°C"/>
<object uri="/120/10101/0/0/12103" name="Mandata a +10°C"/>
<object uri="/120/10101/0/0/12107" name="Abbassamento mandata"/>
</object>
<object uri="/120/10101/12095/0/0" name="Temperatura esterna ritardata">
<object uri="/120/10101/12095/0/1071" name="Lag x"/>
<object uri="/120/10101/12095/0/1072" name="Lag Tf"/>
<object uri="/120/10101/12095/0/1073" name="Lag y"/>
</object>
<object uri="/120/10101/0/0/12096" name="Limite temp. giorno"/>
<object uri="/120/10101/0/0/12097" name="Limite temp. notte"/>
<object uri="/120/10101/0/0/12100" name="Temperatura di abilitazione"/>
<object uri="/120/10101/0/0/12215" name="Temperatura di abilitazione"/>
<object uri="/120/10101/0/11124/0" name="Pompa di riscaldamento">
<object uri="/120/10101/0/11124/2001" name="Richiesta"/>
</object>
<object uri="/120/10101/0/0/12652" name="Smaltimento solare"/>
</object>
<object uri="/120/10101/0/0/12182" name="Altro">
<object uri="/120/10101/0/0/12125" name="Tasto Giorno"/>
<object uri="/120/10101/0/0/12126" name="Tasto Auto"/>
<object uri="/120/10101/0/0/12230" name="Tasto Notte"/>
<object uri="/120/10101/0/0/12080" name="Tasto ON/OFF"/>
<object uri="/120/10101/0/0/12218" name="Tasto Rientra"/>
<object uri="/120/10101/0/0/12231" name="Tasto Esci"/>
<object uri="/120/10101/0/0/12232" name="Inizio ferie"/>
<object uri="/120/10101/0/0/12239" name="Fine ferie"/>
</object>
</fub>
<fub uri="/40/10021" name="Caldaia">
<object uri="/40/10021/0/0/12010" name="Stato contatori">
<object uri="/40/10021/0/0/12153" name="Ore carico nominale"/>
<object uri="/40/10021/0/0/12016" name="Consumo totale"/>
<object uri="/40/10021/0/0/12014" name="Consumo da ultima manutenzione"/>
<object uri="/40/10021/0/0/12011" name="Volume recipiente pellet"/>
<object uri="/40/10021/0/0/12012" name="Consumo da ultimo asporto cenere"/>
<object uri="/40/10021/0/0/12013" name="Consumo da ultimo svuotamento box cenere"/>
</object>
<object uri="/40/10021/0/0/12000" name="Caldaia">
<object uri="/40/10021/0/0/12421" name="Impostazioni"/>
<object uri="/40/10021/0/0/12180" name="Pressione caldaia"/>
<object uri="/40/10021/0/0/12161" name="Caldaia">
<object uri="/40/10021/0/0/12001" name="Valore nominale caldaia"/>
<object uri="/40/10021/0/0/12317" name="Cascata"/>
</object>
<object uri="/40/10021/0/0/12300" name="Caldaia inferiore"/>
<object uri="/40/10021/0/0/12078" name="Regolatore mandata 1">
<object uri="/40/10021/0/11128/0" name="Valvola di commutazione">
<object uri="/40/10021/0/11128/2001" name="Richiesta"/>
</object>
<object uri="/40/10021/0/11121/0" name="Miscelatore mandata 1">
<object uri="/40/10021/0/11121/2120" name="Temperatura nom."/>
<object uri="/40/10021/0/11121/2002" name="Stato"/>
<object uri="/40/10021/0/11121/2121" name="Temperatura reale"/>
<object uri="/40/10021/0/11121/2127" name="Posizione"/>
</object>
<object uri="/40/10021/0/11123/0" name="Pompa caldaia">
<object uri="/40/10021/0/11123/2001" name="Richiesta"/>
<object uri="/40/10021/0/11123/2130" name="Uscita"/>
</object>
</object>
<object uri="/40/10021/0/0/12162" name="Gas di scarico">
<object uri="/40/10021/0/0/13266" name="Misurazione emissioni">
<object uri="/40/10021/0/0/12116" name="Tipo di misurazione"/>
<object uri="/40/10021/0/0/13267" name="Inizio della misurazione"/>
<object uri="/40/10021/0/0/13268" name="Durata blocco"/>
<object uri="/40/10021/0/0/13269" name="Avviare ora"/>
<object uri="/40/10021/0/0/13277" name="Disattivare misurazione"/>
</object>
</object>
<object uri="/40/10021/0/0/12165" name="Ventilatore fumi"/>
<object uri="/40/10021/0/0/12164" name="Ossigeno residuo"/>
<object uri="/40/10021/0/0/12050" name="Estrazione ceneri">
<object uri="/40/10021/0/0/12248" name="Inizio periodo di riposo"/>
<object uri="/40/10021/0/0/12249" name="Durata periodo di riposo"/>
<object uri="/40/10021/0/0/12012" name="Consumo da ultimo asporto cenere"/>
<object uri="/40/10021/0/0/12013" name="Consumo da ultimo svuotamento box cenere"/>
<object uri="/40/10021/0/0/12120" name="Svuota box cenere dopo"/>
<object uri="/40/10021/0/0/12014" name="Consumo da ultima manutenzione"/>
</object>
<object uri="/40/10021/0/0/12005" name="Recipiente Pellet">
<object uri="/40/10021/0/0/12071" name="Rabbocca recipiente pellet"/>
<object uri="/40/10021/0/0/12011" name="Volume recipiente pellet"/>
<object uri="/40/10021/0/0/12152" name="Orario di aspirazione"/>
<object uri="/40/10021/0/11042/0" name="Turbina d'aspirazione">
<object uri="/40/10021/0/11042/2001" name="Richiesta"/>
</object>
</object>
</object>
<object uri="/40/10021/0/0/12182" name="Altro">
<object uri="/40/10021/0/0/12080" name="Tasto ON/OFF"/>
<object uri="/40/10021/0/0/12112" name="Tasto pulizia"/>
<object uri="/40/10021/0/0/12152" name="Orario di aspirazione"/>
</object>
</fub>
<fub uri="/40/10201" name="Deposito">
<object uri="/40/10201/0/0/12058" name="Estrazione combustibile"/>
<object uri="/40/10201/0/0/12015" name="Scorta"/>
<object uri="/40/10201/0/0/12042" name="Limite di avviso Scorta"/>
</fub>
<fub uri="/40/10241" name="ester.">
<object uri="/40/10241/0/0/10990" name="Entrate">
<object uri="/40/10241/0/0/12197" name="Temperatura esterna"/>
</object>
<object uri="/40/10241/0/0/12256" name="Sistema">
<object uri="/40/10241/0/0/12197" name="Temperatura esterna"/>
</object>
</fub>
</menu>
</eta>

**Comment by benjamin-becht** [comment]
> Hello Nigl, I have looked into this, I have the same issue to not be able to select outside temperature sensor from the dropdown-menu. As this sensor is within its own section (like "boiler", this sensor sits in area "sys" as one single unit) either that section is not available (according to the XML output from ETA heating at /user/menu) but is reference within other sections.
> 
> For example outside temperature is referenced within the solar collector with object-id: 120/10221/0/0/12197 And within other others as well, but after closing an object-tag, opened as separate object. Maybe this helps you finding it.
> 
> Here is the XML section for reference:

`<object uri="/120/10221/0/0/19408" name="Solaranlage">
<object uri="/120/10221/0/0/19391" name="Ergänzung"/>
<object uri="/120/10221/0/0/12275" name="Kollektor">
<object uri="/120/10221/0/0/12187" name="Kollektor Min"/>
<object uri="/120/10221/0/0/12188" name="Kollektor Max"/>
<object uri="/120/10221/0/0/12189" name="Warnung Nacht"/>
<object uri="/120/10221/0/0/12197" name="Außentemperatur"/>
</object>
<object uri="/120/10221/0/0/12641" name="Startfunktion">
<object uri="/120/10221/0/0/12642" name="Beginn"/>
<object uri="/120/10221/0/0/12643" name="Ende"/>
<object uri="/120/10221/0/0/12131" name="Frostschutz"/>
<object uri="/120/10221/0/0/12040" name="Laufzeit"/>
<object uri="/120/10221/0/0/12644" name="Zykluszeit"/>
</object>
<object uri="/120/10221/0/0/12278" name="Kollektorpumpe">
<object uri="/120/10221/0/0/12275" name="Kollektor"/>
<object uri="/120/10221/0/0/12781" name="Speicher 1 unten"/>
<object uri="/120/10221/0/0/12186" name="Soll Differenz Kollektor"/>
<object uri="/120/10221/0/0/12227" name="Mindest Drehzahl"/>
<object uri="/120/10221/0/0/12133" name="Einschaltdifferenz"/>
<object uri="/120/10221/0/0/12141" name="Ausschaltdifferenz"/>
</object>
</object>`

**Comment by nigl** [comment]
@joeto60 @benjamin-becht sorry for the late response...

Thank you @benjamin-becht for your research.

One possible solution could be also to allow also parent objects in the menu to be valid sensors.

I will try to evaluate this

**Comment by nigl** [comment]
@joeto60 @benjamin-becht  I released a new version, It should work now
