### ISSUE TITLE
Can not add repository

### ISSUE THREAD

**Issue by LucianoHradsky** [nigl/homeassistant_eta_integration#9]
Hi Guys,
tried to follow instructions to integrate to HA. I am getting eror: https://github.com/nigl/homeassistant_eta_integration is not a valid add-on repository

Any idea where could be a problem?

Thank you for this work!

**Comment by nigl** [comment]
Hi @LucianoHradsky,
have you used HACS to integrate the this add on?
I tried it on my Homeassistant and I could add it following the steps in the README.md
Regards
nigl

**Comment by N1Dy** [comment]
Hello,

link to add the repo to HACS run without any problem
![image](https://github.com/nigl/homeassistant_eta_integration/assets/66574807/552700da-826e-4bab-9362-0fac19c4b927)

But in the README.md is a different name 
>Click on "userdefined repositories"
you need to click on "custom repositories"

**Comment by nigl** [comment]
@N1Dy thank you, I fixed the readme.md
